version: '3.8'

services:
  mysql:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: johnson

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080


  node:
    image: node:18-alpine
    volumes:
      - ./:/root/src
    restart: unless-stopped
    command: tail -f /dev/null 

